#!/sbin/openrc-run
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="Omnissa Horizon Serial Port Service"
command="/usr/lib64/omnissa/horizon/bin/ftsprhvd"
command_background="yes"
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
	need localmount
	use net logger
	after bootmisc
}

start_pre() {
	checkpath --directory --mode 0755 /run
}

